#W_Bot电机数据类型

#钛虎-上肢电机
devices_pkg/Motor left_shoulder_pitch
devices_pkg/Motor left_shoulder_roll
devices_pkg/Motor left_shoulder_yaw
devices_pkg/Motor left_elbow
devices_pkg/Motor left_wrist_yaw
devices_pkg/Motor left_wrist_pitch
devices_pkg/Motor left_wrist_roll

devices_pkg/Motor right_shoulder_pitch
devices_pkg/Motor right_shoulder_roll
devices_pkg/Motor right_shoulder_yaw
devices_pkg/Motor right_elbow
devices_pkg/Motor right_wrist_yaw
devices_pkg/Motor right_wrist_pitch
devices_pkg/Motor right_wrist_roll

devices_pkg/Motor head_pitch
devices_pkg/Motor head_yaw






