#W_Bot数据类型

#意优-下肢电机
devices_pkg/Motor waist_roll
devices_pkg/Motor waist_yaw
devices_pkg/Motor knee
devices_pkg/Motor hip
devices_pkg/Motor ankel
devices_pkg/Motor ankel_right

#钛虎-上肢电机
devices_pkg/Motor left_shoulder_pitch
devices_pkg/Motor left_shoulder_roll
devices_pkg/Motor left_shoulder_yaw
devices_pkg/Motor left_elbow
devices_pkg/Motor left_wrist_yaw
devices_pkg/Motor left_wrist_pitch
devices_pkg/Motor left_wrist_roll

devices_pkg/Motor right_shoulder_pitch
devices_pkg/Motor right_shoulder_roll
devices_pkg/Motor right_shoulder_yaw
devices_pkg/Motor right_elbow
devices_pkg/Motor right_wrist_yaw
devices_pkg/Motor right_wrist_pitch
devices_pkg/Motor right_wrist_roll

devices_pkg/Motor head_pitch
devices_pkg/Motor head_yaw

#本末-底盘电机


#IMU
devices_pkg/IMU chest
devices_pkg/IMU chassis




