#W_Bot电机数据类型

#意优-下肢电机
devices_pkg/WBottem waist_roll
devices_pkg/WBottem waist_yaw
devices_pkg/WBottem knee
devices_pkg/WBottem hip
devices_pkg/WBottem ankle

#钛虎-上肢电机
devices_pkg/WBottem left_shoulder_pitch
devices_pkg/WBottem left_shoulder_roll
devices_pkg/WBottem left_shoulder_yaw
devices_pkg/WBottem left_elbow
devices_pkg/WBottem left_wrist_yaw
devices_pkg/WBottem left_wrist_pitch
devices_pkg/WBottem left_wrist_roll

devices_pkg/WBottem right_shoulder_pitch
devices_pkg/WBottem right_shoulder_roll
devices_pkg/WBottem right_shoulder_yaw
devices_pkg/WBottem right_elbow
devices_pkg/WBottem right_wrist_yaw
devices_pkg/WBottem right_wrist_pitch
devices_pkg/WBottem right_wrist_roll

devices_pkg/WBottem head_pitch
devices_pkg/WBottem head_yaw

#本末-底盘电机
devices_pkg/WBottem wheel_left
devices_pkg/WBottem wheel_right





